
version: '3.1'

services:

  mongo:
    image: mongo
    #restart: always
    volumes:
        - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081

volumes:
  mongo-data:
    driver: local