
version: '3.1'

services:

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    #restart: always
    volumes:
        - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8080:8081
    volumes:
        - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local